### ISSUE TITLE
Upgrade MODS support from 3.3/4 to 3.6

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/infrastructure-stories#1]
This is a backwards compatible updates to the MODS specification that introduces new attributes, at least one, a nameIdentifier, related to linked data. MODS schema version is declared in three places:

1. In DOR Services code that generates a stub descMetadata datastream

- New header (only schema number is changed): 
```
<mods:mods xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.xsd" version="3.6">
```
- Responsibility: infrastructure group
- Currently producing MODS 3.3

2. In the /catalog service MARC to MODS conversion used to Fetch MODS from symphony 

- Determined by which MARC-to-MODS xslt is invoked by the /catalog service
- Responsibility: Metadata, Arcadia Falcone
   - Arcadia to install new XSLT, either the LoC version or modified as needed (bug fixes or local customizations)
   - Work with infrastructure group to deploy

3. In the MODS generated by Modsulator for spreadsheet upload

- Responsibility: Metadata, Arcadia Falcone
   - Arcadia to install new Spreadsheet master and MODS template, either the LoC version or modified as needed (bug fixes or local customizations)
   - Work with infrastructure group to deploy
   - See https://jirasul.stanford.edu/jira/browse/META-42

Note: supercedes https://jirasul.stanford.edu/jira/browse/JUMBO-36 and https://github.com/sul-dlss/mods/issues/24

**Comment by LynnMcRae** [comment]
This is an old ticket that might no longer be relevant. Passing to Arcadia for disposition.

**Comment by arcadiafalcone** [comment]
All the processes listed above now use MODS 3.6. Hydrus still generates MODS 3.3.
